### ISSUE TITLE
Transponder Code Issue

### ISSUE THREAD

**Issue by The-MG** [Pomax/msfs-simconnect-api-wrapper#28]
When trying to fetch the transponder code: 
```
const stop = api.schedule(
      (data) => {
        console.log(data);
      },
      500,
      "TRANSPONDER CODE:index",
      "PLANE LONGITUDE",
      "PLANE LATITUDE"
    );
```
    
    It sends this error: 
```
throw RangeError("Illegal offset: 0 <= "+offset+" (+"+8+") <= "+this.buffer.length);
                ^
RangeError: Illegal offset: 0 <= 40 (+8) <= 44
```

Is there any fix?

**Comment by Pomax** [comment]
You need a real index though, not `TRANSPONDER CODE:index`. What happens when you use `TRANSPONDER CODE:1`?

**Comment by The-MG** [comment]
> You need a real index though, not the literal string `TRANSPONDER CODE:index` (the "index" part indicates that something has to go there, in this case [a 4 digit code](https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Aircraft_SimVars/Aircraft_RadioNavigation_Variables.htm#TRANSPONDER_CODE)). What happens when you use `TRANSPONDER CODE:1111` or whatever transport code you're working with?

Setting it to `TRANSPONDER CODE:1111` gives me the same error as before.

**Comment by Pomax** [comment]
nice, then we have something to debug. Let me fire up a Beaver on CYYJ and see what's going on.

**Comment by Pomax** [comment]
Not sure how to debug this one, tbh. If I set the transponder to standy, or just "on", `TRANSPONDER_STATE` keeps saying 0, meaning MSFS sees the transponder as being off.

**Comment by The-MG** [comment]
I had the same issue.

**Comment by Pomax** [comment]
This might be one of those "see if node-simconnect does the same thing, and if so... that might actually be a simconnect bug". Do you have FSUIPC? Does that do the right thing? =/

**Comment by The-MG** [comment]
I wouldn't even know how to setup the node-simconnect instance. I have FSUIPC, but again not sure how to set it up.

**Comment by Pomax** [comment]
Come to think of it,  we don't even need FSUIPC. If you install both the MSFS SDK and samples from within the game (turn on developer options from the general options, then use the dev toolbar to install those) that gets you a dir called `\SDK\Samples\VisualStudio\SimvarWatcher\bin\x64\Release` with a `Simvars.exe`, which is MSFS's own simvar watcher application.

We can run that while the game's running, and in the good old tradition of SimConnect it looks like the docs lie about what the index is: the simwatcher only lets you pick values 0 through 99, based on your primary/standby transponder, so that `TRANSPONDER CODE:1` is the primary, and `TRANSPONDER CODE:2` your standby. (What 3 through 99 are for, I have no idea)

**Comment by The-MG** [comment]
I am unsure of what changed it, but in the simconnect wrapper the TRANSPONDER_CODE:1 is now working! Thank you so much!

**Comment by Pomax** [comment]
Nothing changed. We're just using the correct index now.
